name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  deploy:
    name: Deploy to Staging
    needs: ci
    uses: testorg/devops/.github/workflows/deploy.yml@main
    with:
      APP_ENV: stage
    secrets: inherit
