name: Staging and Certification

on:
  workflow_dispatch:  # manual trigger

jobs:

## k8s-c01-c Staging ##
  k8s-c01-c_stg_approval:
    name: Start k8s-c01-c Staging
    environment: k8s-c01-c_stg
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        run: echo "Approval required for Staging Start"
      
  k8s-c01-c_stg_start_email_G1:
    name: Staging k8s-c01-c Start Email G1
    needs: k8s-c01-c_stg_approval
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Start Email G1
        run: echo "Sending Staging Start Email"
      
  k8s-c01-c_stg_updated_G1:
    name: Staging k8s-c01-c Updated G1
    needs: k8s-c01-c_stg_start_email_G1
    runs-on: ubuntu-latest
    steps: 
      - name: Patching start
        run: echo "Patching"
      
  k8s-c01-c_stg_end_email_G1:
    name: k8s-c01-c Staging Agents end email G1
    needs: k8s-c01-c_stg_updated_G1
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Agents end email G1
        run: echo "Sending Staging Agents end email"

  k8s-c01-c_stg_start_email_G2:
    name: Staging k8s-c01-c Start Email G2
    needs: k8s-c01-c_stg_approval
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Start Email G2
        run: echo "Sending Staging Start Email"
      
  k8s-c01-c_stg_updated_G2:
    name: Staging k8s-c01-c Updated G2
    needs: k8s-c01-c_stg_start_email_G2
    runs-on: ubuntu-latest
    steps: 
      - name: Patching start
        run: echo "Patching"
      
  k8s-c01-c_stg_end_email_G2:
    name: k8s-c01-c Staging Agents end email G2
    needs: k8s-c01-c_stg_updated_G2
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Agents end email G2
        run: echo "Sending Staging Agents end email"
      
## k8s-c01-w Staging ##
  k8s-c01-w_stg_approval:
    name: Start k8s-c01-w Staging 
    environment: k8s-c01-w_stg
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        run: echo "Approval required for Staging Start"
      
  k8s-c01-w_stg_start_email_G1:
    name: Staging k8s-c01-w Start Email G1
    needs: k8s-c01-w_stg_approval
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Start Email G1
        run: echo "Sending Staging Start Email"
      
  k8s-c01-w_stg_updated_G1:
    name: Staging k8s-c01-w Updated
    needs: k8s-c01-w_stg_start_email_G1
    runs-on: ubuntu-latest
    steps: 
      - name: Patching start G1
        run: echo "Patching"
      
  k8s-c01-w_stg_end_email_G1:
    name: k8s-c01-w Staging Agents end email G1
    needs: k8s-c01-w_stg_updated_G1
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Agents end email G1
        run: echo "Sending Staging Agents end email"

  k8s-c01-w_stg_start_email_G2:
    name: Staging k8s-c01-w Start Email G2
    needs: k8s-c01-w_stg_approval
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Start Email G2
        run: echo "Sending Staging Start Email"
      
  k8s-c01-w_stg_updated_G2:
    name: Staging k8s-c01-w Updated G2
    needs: k8s-c01-w_stg_start_email_G2
    runs-on: ubuntu-latest
    steps: 
      - name: Patching start G2
        run: echo "Patching"
      
  k8s-c01-w_stg_end_email_G2:
    name: k8s-c01-w Staging Agents end email G2
    needs: k8s-c01-w_stg_updated_G2
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Agents end email G2
        run: echo "Sending Staging Agents end email"

## Rancher Staging ##
  rancher_stg_approval:
    name: Start Rancher Staging 
    environment: rancher_stg
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        run: echo "Approval required for Staging Start"
      
  rancher_stg_start_email:
    name: Staging Rancher Start Email
    needs: rancher_stg_approval
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Start Email
        run: echo "Sending Staging Start Email"
      
  rancher_stg_updated:
    name: Staging Rancher Updated
    needs: rancher_stg_start_email
    runs-on: ubuntu-latest
    steps: 
      - name: Patching start
        run: echo "Patching"
      
  rancher_stg_end_email:
    name: Rancher Staging Agents end email
    needs: rancher_stg_updated
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Agents end email
        run: echo "Sending Staging Agents end email"

## Redis Staging ##
  redis_stg_approval:
    name: Start Redis Staging 
    environment: redis_stg
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        run: echo "Approval required for Staging Start"
      
  redis_stg_start_email_G1:
    name: Staging Redis g Start Email G1
    needs: redis_stg_approval
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Start Email G1
        run: echo "Sending Staging Start Email G1"
      
  redis_stg_updated_G1:
    name: Staging redis Updated G1
    needs: redis_stg_start_email_G1
    runs-on: ubuntu-latest
    steps: 
      - name: Patching start G1
        run: echo "Patching G1"
      
  redis_stg_end_email_G1:
    name: Redis Staging Agents end email G1
    needs: redis_stg_updated_G1
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Agents end email G1
        run: echo "Sending Staging Agents end email G1"

  redis_stg_start_email_G2:
    name: Staging Redis g Start Email G2
    needs: redis_stg_approval
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Start Email G2
        run: echo "Sending Staging Start Email G2"
      
  redis_stg_updated_G2:
    name: Staging redis Updated G2
    needs: redis_stg_start_email_G2
    runs-on: ubuntu-latest
    steps: 
      - name: Patching start G2
        run: echo "Patching G2"
      
  redis_stg_end_email_G2:
    name: Redis Staging Agents end email G2
    needs: redis_stg_updated_G2
    runs-on: ubuntu-latest
    steps:
      - name: Send Staging Agents end email G2
        run: echo "Sending Staging Agents end email G2"


## Redis Certification ##
  redis_crt_approval_G1:
    name: Start Certification G1
    environment: redis_crt
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval G1
        run: echo "Approval required for Certification Start G1"
      
  redis_crt_start_email_G1:
    name: Certification Start Email G1
    needs: redis_crt_approval_G1
    runs-on: ubuntu-latest
    steps:
      - name: Send Certification Start Email G1
        run: echo "Sending Certification Start Email G1"
      
  redis_crt_updated_G1:
    name: Certification Updated G1
    needs: redis_crt_start_email_G1
    runs-on: ubuntu-latest
    steps: 
      - name: Patching start G1
        run: echo "Patching G1"
      
  redis_crt_end_email_G1:
    name: Certification Agents end email G1
    needs: redis_crt_updated_G1
    runs-on: ubuntu-latest
    steps:
      - name: Send Certification Agents end email G1
        run: echo "Sending Certification Agents end email G1"
        
  redis_crt_approval_G2:
    name: Start Certification G2
    needs: redis_stg_end_email_G2
    environment: redis_crt
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval G2
        run: echo "Approval required for Certification Start G2"
      
  redis_crt_start_email_G2:
    name: Certification Start Email G2
    needs: redis_crt_approval_G2
    runs-on: ubuntu-latest
    steps:
      - name: Send Certification Start Email G2
        run: echo "Sending Certification Start Email G2"
      
  redis_crt_updated_G2:
    name: Certification Updated G2
    needs: redis_crt_start_email_G2
    runs-on: ubuntu-latest
    steps: 
      - name: Patching start G2
        run: echo "Patching G2"
      
  redis_crt_end_email_G2:
    name: Certification Agents end email G2
    needs: redis_crt_updated_G2
    runs-on: ubuntu-latest
    steps:
      - name: Send Certification Agents end email G2
        run: echo "Sending Certification Agents end email G2"
