name: Development

on:
  workflow_dispatch:  # manual trigger

jobs:

## Docker Approval ##
  docker_dev_approval:
    name: Start Docker Dev
    environment: docker_dev
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        run: echo "Approval required for Dev Start"
      
  docker_dev_start_email_G1:
    name: Dev Docker Start Email G1
    needs: docker_dev_approval
    runs-on: ubuntu-latest
    steps:
      - name: Send Dev Start Email
        run: echo "Sending Dev Start Email"
        
  docker_dev_start_email_G2:
    name: Dev Docker Start Email G2 
    needs: docker_dev_approval
    runs-on: ubuntu-latest
    steps:
      - name: Send Dev Start Email
        run: echo "Sending Dev Start Email"  
        
  docker_dev_updated_G1:
    name: Dev Docker Updated G1
    needs: docker_dev_start_email_G1
    runs-on: ubuntu-latest
    steps: 
      - name: Patching start
        run: echo "Patching"

  docker_dev_updated_G2:
    name: Dev Docker Updated G2
    needs: docker_dev_start_email_G2
    runs-on: ubuntu-latest
    steps: 
      - name: Patching start
        run: echo "Patching"
      
  docker_dev_end_email_G1:
    name: Dev Docker Agents end email G1
    needs: docker_dev_updated_G1
    runs-on: ubuntu-latest
    steps:
      - name: Send Dev Agents end email
        run: echo "Sending Dev Agents end email"
          
  docker_dev_end_email_G2:
    name: Dev Docker Agents end email G2
    needs: docker_dev_updated_G2
    runs-on: ubuntu-latest
    steps:
      - name: Send Dev Agents end email
        run: echo "Sending Dev Agents end email"
